import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#05070A" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#11141D",
  },
  headerTitle: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  publishText: { color: "#4CC9F0", fontWeight: "bold", fontSize: 16 },

  scrollContent: { padding: 25 },
  label: {
    color: "#4CC9F0",
    fontSize: 11,
    fontWeight: "bold",
    marginBottom: 10,
    letterSpacing: 1,
  },
  input: {
    backgroundColor: "#11141D",
    borderRadius: 12,
    color: "#FFF",
    padding: 15,
    marginBottom: 25,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#1A1E2E",
  },
  textArea: { minHeight: 120, textAlignVertical: "top" },
  uploadBox: {
    height: 180,
    backgroundColor: "#11141D",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1A1E2E",
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 25,
    overflow: "hidden",
  },
  previewImage: { width: "100%", height: "100%" },
  uploadText: {
    color: "#4CC9F0",
    fontSize: 12,
    marginTop: 8,
    fontWeight: "500",
  },
  pdfPicker: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#11141D",
    padding: 18,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1A1E2E",
    marginBottom: 25,
  },
  pdfPickerText: { color: "#444", marginLeft: 12, fontSize: 14, flex: 1 },
  typeSelector: { flexDirection: "row", gap: 15, marginBottom: 30 },
  typeBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#4CC9F0",
  },
  typeBtnActive: { backgroundColor: "#4CC9F0" },
  typeBtnText: { color: "#4CC9F0", fontWeight: "bold", fontSize: 12 },
  typeBtnTextActive: { color: "#000" },
});
